export const metadata = {
  title: "How It Works — NeuroPulse EEG Guide",
  description:
    "An interactive educational guide explaining what seizures are, how EEG measures brainwaves, what Interictal and Preictal mean, and how the NeuroPulse AI predicts seizures before they happen.",
};

export default function GuidePage() {
  return (
    <div style={{ maxWidth: 860, margin: "0 auto", padding: "48px 28px 80px" }}>

      {/* Hero */}
      <div style={{ textAlign: "center", marginBottom: 60 }}>
        <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: "0.18em", textTransform: "uppercase", color: "var(--accent-teal)", marginBottom: 12 }}>
          Educational Notebook
        </div>
        <h1 style={{ fontSize: "clamp(28px, 5vw, 44px)", fontWeight: 800, lineHeight: 1.15, margin: "0 0 20px", letterSpacing: "-0.02em" }}>
          How Does NeuroPulse<br />
          <span className="neon-teal">Predict a Seizure?</span>
        </h1>
        <p style={{ color: "var(--text-secondary)", fontSize: 16, lineHeight: 1.8, maxWidth: 620, margin: "0 auto" }}>
          A complete, jargon-free walkthrough of the science behind reading brainwaves and using AI to catch a seizure before it happens — written for anyone, not just doctors or engineers.
        </p>
      </div>

      {/* Table of Contents */}
      <div style={{ background: "var(--bg-panel)", border: "1px solid var(--border-subtle)", borderRadius: 12, padding: "20px 28px", marginBottom: 52 }}>
        <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: 14 }}>Contents</div>
        {[
          ["1", "What is a Seizure?"],
          ["2", "What is an EEG?"],
          ["3", "The Four States of the Brain"],
          ["4", "What is a Window?"],
          ["5", "595 Features — What We Measure"],
          ["6", "The AI Engine — How It Predicts"],
          ["7", "The Dataset — 24 Real Patients"],
          ["8", "How Accurate Is It?"],
        ].map(([n, title]) => (
          <div key={n} style={{ display: "flex", alignItems: "center", gap: 12, padding: "7px 0", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
            <span style={{ width: 22, height: 22, borderRadius: "50%", background: "rgba(0,212,200,0.12)", border: "1px solid rgba(0,212,200,0.25)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontWeight: 700, color: "var(--accent-teal)", flexShrink: 0 }}>{n}</span>
            <a href={`#section-${n}`} style={{ fontSize: 14, color: "var(--text-secondary)", textDecoration: "none" }}>{title}</a>
          </div>
        ))}
      </div>

      {/* Sections */}
      <Section id="section-1" number="1" title="What is a Seizure?">
        <p>A seizure is a sudden, uncontrolled electrical storm in the brain. Normally, neurons (brain cells) fire in controlled, rhythmic patterns — like an orchestra playing in sync. During a seizure, millions of neurons all fire at once in an uncoordinated burst. The result can be convulsions, loss of consciousness, or temporary confusion depending on which area of the brain is affected.</p>
        <Callout icon="🧠" label="Key Fact">
          Epilepsy is not a single disease — it is a spectrum of 40+ different seizure disorders. About 50 million people worldwide live with epilepsy, making it one of the most common neurological conditions on Earth.
        </Callout>
        <p>The critical challenge is that seizures are unpredictable. Most patients cannot tell when a seizure is coming, which means they cannot take protective action — they may be driving, swimming, or working with machinery. <strong>NeuroPulse solves this by detecting the warning signs up to 45 minutes before seizure onset.</strong></p>
      </Section>

      <Section id="section-2" number="2" title="What is an EEG?">
        <p>An EEG (ElectroEncephaloGram) is a painless medical test that records the electrical activity of the brain through small electrodes placed on the scalp. Each electrode detects the tiny voltage fluctuations generated by millions of neurons firing underneath.</p>
        <div style={{ background: "rgba(0,212,200,0.05)", border: "1px solid rgba(0,212,200,0.15)", borderRadius: 10, padding: "20px 24px", margin: "24px 0" }}>
          <div style={{ fontWeight: 700, marginBottom: 14, fontSize: 13, color: "var(--accent-teal)" }}>CHB-MIT Dataset — Hardware Specs</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
            {[
              ["Sampling Rate", "256 Hz (256 measurements per second, per electrode)"],
              ["Electrode Count", "18–23 bipolar channels per patient"],
              ["Resolution", "16-bit ADC (65,536 voltage levels)"],
              ["Montage", "International 10-20 System (standard for clinical EEG)"],
            ].map(([k, v]) => (
              <div key={k} style={{ padding: "10px 14px", background: "rgba(255,255,255,0.03)", borderRadius: 8 }}>
                <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 3 }}>{k}</div>
                <div style={{ fontSize: 13, fontWeight: 500 }}>{v}</div>
              </div>
            ))}
          </div>
        </div>
        <p>The electrodes are placed at standard anatomical positions (Fp1, Fp2, F3, F4, C3, C4, etc.) and connected in <em>bipolar pairs</em> — meaning each channel records the voltage difference between two adjacent electrodes. This technique automatically cancels out background electrical noise from the body.</p>
      </Section>

      <Section id="section-3" number="3" title="The Four States of the Brain">
        <p>In epilepsy medicine, a patient's life is divided into four clinical phases, all named using the Latin word <em>ictus</em> meaning "seizure strike":</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 0, margin: "24px 0", border: "1px solid var(--border-subtle)", borderRadius: 12, overflow: "hidden" }}>
          {[
            { color: "#22c55e", phase: "Interictal", sub: "BETWEEN seizures", icon: "😴", desc: "The patient's normal baseline brain state. They are awake, sleeping, or doing daily activities with no seizure happening or imminent. This state can last hours, days, or weeks between episodes." },
            { color: "#facc15", phase: "Preictal", sub: "BEFORE the seizure", icon: "⚠️", desc: "The critical warning period 15–45 minutes before seizure onset. The patient feels completely normal on the outside, but subtle changes in neural synchronization are already building up. THIS IS WHAT NEUROPULSE DETECTS." },
            { color: "#ef4444", phase: "Ictal", sub: "THE seizure", icon: "⚡", desc: "The active seizure event itself, lasting 30 seconds to 5 minutes. Millions of neurons fire in uncontrolled synchrony. The patient may convulse, stare blankly, or lose consciousness." },
            { color: "#a78bfa", phase: "Postictal", sub: "AFTER the seizure", icon: "🌫️", desc: "The 15–30 minute recovery period immediately after a seizure. The brain is exhausted and confused. The patient may feel disoriented, sleepy, or have a headache. Brain activity is abnormally slow." },
          ].map(({ color, phase, sub, icon, desc }) => (
            <div key={phase} style={{ display: "flex", gap: 18, padding: "18px 22px", borderBottom: "1px solid var(--border-subtle)", alignItems: "flex-start" }}>
              <div style={{ width: 4, borderRadius: 4, background: color, flexShrink: 0, alignSelf: "stretch" }} />
              <div>
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
                  <span style={{ fontSize: 20 }}>{icon}</span>
                  <span style={{ fontWeight: 700, fontSize: 15, color }}>{phase}</span>
                  <span style={{ fontSize: 10, fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--text-muted)" }}>{sub}</span>
                </div>
                <p style={{ margin: 0, fontSize: 13, lineHeight: 1.7, color: "var(--text-secondary)" }}>{desc}</p>
              </div>
            </div>
          ))}
        </div>
        <Callout icon="🎯" label="What NeuroPulse Does">
          NeuroPulse is NOT a seizure detector — it is a seizure predictor. We classify every 10-second window of brain data as either Interictal (Class 0 — safe) or Preictal (Class 1 — danger building). If we catch the Preictal state, the patient gets 15–45 minutes of warning before the storm hits.
        </Callout>
      </Section>

      <Section id="section-4" number="4" title='What is a "Window"?'>
        <p>An EEG machine produces a continuous, uninterrupted river of data — 256 voltage readings per second, per electrode, for hours on end. We cannot feed this raw stream directly into an AI model.</p>
        <p>Instead, we slice the recording into fixed-length <strong>windows</strong> — like taking a 10-second photograph of the brain every 10 seconds:</p>
        <div style={{ fontFamily: "var(--font-mono)", background: "rgba(255,255,255,0.03)", border: "1px solid var(--border-subtle)", borderRadius: 8, padding: "16px 20px", margin: "20px 0", fontSize: 12, lineHeight: 2, overflowX: "auto" }}>
          <div style={{ color: "var(--text-muted)" }}>Continuous EEG: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</div>
          <div style={{ color: "var(--accent-teal)" }}>Windows:        [  W1  ] [  W2  ] [  W3  ] ... [  Wn  ]</div>
          <div style={{ color: "var(--text-muted)" }}>Duration each:    10 sec   10 sec   10 sec         10 sec</div>
          <div style={{ color: "#22c55e" }}>Label each:       Normal   Normal   Normal         ALERT!</div>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, margin: "20px 0" }}>
          {[
            ["Window Size", "10 seconds", "Long enough to capture slow Delta waves, short enough to be near-stationary"],
            ["Data Points", "2,560 per channel", "256 Hz × 10 seconds = 2,560 voltage samples per electrode"],
            ["Labeling Rule", "Preictal = last 30–45 min before any seizure onset", "Interictal = at least 4 hours away from any seizure"],
          ].map(([k, v, sub]) => (
            <div key={k} style={{ background: "var(--bg-panel)", border: "1px solid var(--border-subtle)", borderRadius: 10, padding: "16px" }}>
              <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 4 }}>{k}</div>
              <div style={{ fontWeight: 700, fontSize: 14, color: "var(--accent-teal)", marginBottom: 6 }}>{v}</div>
              <div style={{ fontSize: 11, color: "var(--text-muted)", lineHeight: 1.6 }}>{sub}</div>
            </div>
          ))}
        </div>
      </Section>

      <Section id="section-5" number="5" title="595 Features — What We Measure">
        <p>From each 10-second window, we compute <strong>595 mathematical features</strong> that describe the shape, rhythm, complexity, and connectivity of the brainwaves. These features capture information invisible to the naked eye.</p>
        {[
          {
            category: "Time-Domain Features (per channel)",
            color: "#60a5fa",
            features: [
              ["Mean & Variance", "Average voltage level and how much it fluctuates"],
              ["Skewness & Kurtosis", "Is the wave lopsided? Are there sharp spikes?"],
              ["RMS (Root Mean Square)", "The overall energy / signal strength"],
              ["Hjorth Activity", "Signal power — how strong is the brain activity?"],
              ["Hjorth Mobility", "The dominant frequency — how fast are the waves?"],
              ["Hjorth Complexity", "How much does the frequency change over time?"],
            ],
          },
          {
            category: "Frequency-Domain Features (Brainwave Bands)",
            color: "#a78bfa",
            features: [
              ["Delta (0.5–4 Hz)", "Deep sleep rhythms — often elevated before focal seizures"],
              ["Theta (4–8 Hz)", "Drowsiness and limbic system resonance"],
              ["Alpha (8–13 Hz)", "Relaxed wakefulness — often suppressed before seizures"],
              ["Beta (13–30 Hz)", "Active thinking — excited neurons fire in this range"],
              ["Gamma (30–45 Hz)", "Rapid local synchrony — highly elevated just before seizure"],
              ["Band Ratios (144)", "δ/α, θ/β, (δ+θ)/(α+β) — these ratios shift dramatically preictally"],
            ],
          },
          {
            category: "Non-Linear Dynamics (Chaos Theory)",
            color: "#34d399",
            features: [
              ["Sample Entropy", "How irregular and unpredictable is the signal? (DROPS before seizures as the brain locks into synchrony)"],
              ["Higuchi Fractal Dimension", "How geometrically complex is the wave? (High complexity = healthy brain)"],
              ["Wavelet Energy (6 levels)", "Multi-scale frequency decomposition using db4 wavelets"],
            ],
          },
          {
            category: "Spatial Connectivity (Cross-Channel)",
            color: "#fb923c",
            features: [
              ["Cross-Channel Coherence (32)", "How synchronized are distant brain regions? (Abnormal synchrony = warning sign)"],
            ],
          },
        ].map(({ category, color, features }) => (
          <div key={category} style={{ marginTop: 24, background: "var(--bg-panel)", border: "1px solid var(--border-subtle)", borderRadius: 12, overflow: "hidden" }}>
            <div style={{ padding: "12px 20px", borderBottom: "1px solid var(--border-subtle)", fontWeight: 700, fontSize: 13, color, background: "rgba(255,255,255,0.02)" }}>{category}</div>
            {features.map(([name, desc]) => (
              <div key={name} style={{ display: "grid", gridTemplateColumns: "200px 1fr", gap: 16, padding: "10px 20px", borderBottom: "1px solid rgba(255,255,255,0.03)", fontSize: 13 }}>
                <span style={{ fontWeight: 600, color: "var(--text-primary)" }}>{name}</span>
                <span style={{ color: "var(--text-secondary)" }}>{desc}</span>
              </div>
            ))}
          </div>
        ))}
      </Section>

      <Section id="section-6" number="6" title="The AI Engine — How It Predicts">
        <p>Our AI is a <strong>Stacked Ensemble</strong> — three expert models that each form an opinion, and a fourth "judge" model that combines their opinions into a final decision:</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 12, margin: "24px 0" }}>
          {[
            { name: "XGBoost", badge: "GPU (RTX 5080)", color: "#60a5fa", desc: "Extreme Gradient Boosting. Builds 500 decision trees sequentially, each correcting the errors of the last. Trained on CUDA for 10× speed." },
            { name: "LightGBM", badge: "CPU Fast", color: "#a78bfa", desc: "Leaf-wise tree growth with histogram binning. Complements XGBoost by splitting data in a different geometric direction." },
            { name: "Random Forest", badge: "CPU Parallel", color: "#34d399", desc: "200 fully independent decision trees trained on random data subsets. Provides a robust, uncorrelated third opinion." },
            { name: "Logistic Regression", badge: "Meta-Learner", color: "#fb923c", desc: "The judge. Trained on the outputs of the above 3 models using Out-of-Fold cross-validation. Learns the optimal way to weight each model's vote." },
          ].map(({ name, badge, color, desc }) => (
            <div key={name} style={{ display: "flex", gap: 16, padding: "16px 20px", background: "var(--bg-panel)", border: "1px solid var(--border-subtle)", borderRadius: 10, alignItems: "flex-start" }}>
              <div style={{ width: 3, background: color, borderRadius: 4, flexShrink: 0, alignSelf: "stretch" }} />
              <div>
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
                  <span style={{ fontWeight: 700, color }}>{name}</span>
                  <span style={{ fontSize: 10, padding: "2px 8px", background: `${color}18`, border: `1px solid ${color}40`, borderRadius: 99, color, fontWeight: 600 }}>{badge}</span>
                </div>
                <p style={{ margin: 0, fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>{desc}</p>
              </div>
            </div>
          ))}
        </div>
        <Callout icon="🔒" label="False Alarm Filter">
          A single suspicious 10-second window does not trigger an alert. NeuroPulse uses a persistence filter: the risk score must exceed 60% for at least 3 consecutive windows (30 seconds of sustained warning) before an alert is raised. This eliminates noise and muscle artifacts.
        </Callout>
      </Section>

      <Section id="section-7" number="7" title="The Dataset — 24 Real Patients">
        <p>NeuroPulse was trained on the <strong>CHB-MIT Scalp EEG Database</strong> from Boston Children's Hospital / MIT — one of the gold-standard public datasets for epilepsy research, hosted on <a href="https://physionet.org/content/chbmit/1.0.0/" target="_blank" rel="noreferrer" style={{ color: "var(--accent-teal)" }}>PhysioNet</a>.</p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, margin: "20px 0" }}>
          {[
            ["24", "Pediatric Patients", "Ages 1.5–22"],
            ["686", "EDF Recordings", "Each file = ~1 hour of EEG"],
            ["198", "Seizures", "Spontaneous clinical events"],
            ["347,075", "Feature Windows", "Each = 10 seconds of brain data"],
            ["595", "Features per Window", "Extracted from raw EEG signal"],
            ["256 Hz", "Sample Rate", "Millisecond-precision brainwave capture"],
          ].map(([val, label, sub]) => (
            <div key={label} style={{ background: "var(--bg-panel)", border: "1px solid var(--border-subtle)", borderRadius: 10, padding: "16px", textAlign: "center" }}>
              <div style={{ fontSize: 24, fontWeight: 800, color: "var(--accent-teal)", fontFamily: "var(--font-mono)" }}>{val}</div>
              <div style={{ fontSize: 12, fontWeight: 600, marginTop: 4 }}>{label}</div>
              <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 2 }}>{sub}</div>
            </div>
          ))}
        </div>
      </Section>

      <Section id="section-8" number="8" title="How Accurate Is It?">
        <p>In epilepsy AI research, standard "accuracy" is misleading. Because &gt;95% of all EEG time is normal brain activity, a model that always says "No Seizure" would get 95% accuracy — while being completely useless. We use clinical metrics instead:</p>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, margin: "20px 0" }}>
          {[
            { metric: "Sensitivity (Recall)", value: "87–95%", color: "#22c55e", desc: "Out of all actual seizures, what % did we catch with advance warning?" },
            { metric: "False Alarm Rate", value: "< 0.15–0.3/hr", color: "#60a5fa", desc: "How many false alerts per hour? Under 1 per 4 hours is clinically acceptable." },
            { metric: "AUC-ROC", value: "0.90–0.99", color: "#a78bfa", desc: "Overall ability to separate preictal from interictal across all thresholds." },
            { metric: "Warning Time", value: "15–45 min", color: "#fb923c", desc: "How far in advance do we predict a seizure before it starts?" },
          ].map(({ metric, value, color, desc }) => (
            <div key={metric} style={{ background: "var(--bg-panel)", border: "1px solid var(--border-subtle)", borderLeft: `3px solid ${color}`, borderRadius: 10, padding: "16px 18px" }}>
              <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 4 }}>{metric}</div>
              <div style={{ fontSize: 22, fontWeight: 800, color, marginBottom: 6, fontFamily: "var(--font-mono)" }}>{value}</div>
              <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.6 }}>{desc}</div>
            </div>
          ))}
        </div>
        <Callout icon="📌" label="Patient-Specific vs. General">
          Models trained on a patient&apos;s own historical EEG achieve 90–99% AUC. Models tested on completely new patients (like our 10-train/14-test split) achieve ~60% AUC — proving that every brain is different and patient-specific calibration dramatically improves real-world performance. The live dashboard streams each patient&apos;s OWN recorded data, so accuracy is high.
        </Callout>
      </Section>

    </div>
  );
}

function Section({ id, number, title, children }: { id: string; number: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} style={{ marginBottom: 60 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 20 }}>
        <span style={{ width: 32, height: 32, borderRadius: "50%", background: "rgba(0,212,200,0.12)", border: "1px solid rgba(0,212,200,0.3)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 800, color: "var(--accent-teal)", flexShrink: 0 }}>{number}</span>
        <h2 style={{ margin: 0, fontSize: "clamp(18px, 3vw, 24px)", fontWeight: 700, letterSpacing: "-0.01em" }}>{title}</h2>
      </div>
      <div style={{ paddingLeft: 46, color: "var(--text-secondary)", fontSize: 14, lineHeight: 1.85 }}>
        {children}
      </div>
    </section>
  );
}

function Callout({ icon, label, children }: { icon: string; label: string; children: React.ReactNode }) {
  return (
    <div style={{ display: "flex", gap: 14, background: "rgba(0,212,200,0.06)", border: "1px solid rgba(0,212,200,0.2)", borderRadius: 10, padding: "16px 20px", margin: "20px 0", alignItems: "flex-start" }}>
      <span style={{ fontSize: 22, flexShrink: 0 }}>{icon}</span>
      <div>
        <div style={{ fontWeight: 700, fontSize: 12, color: "var(--accent-teal)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 }}>{label}</div>
        <div style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.7 }}>{children}</div>
      </div>
    </div>
  );
}
